-- Add subscription fields to cities table
ALTER TABLE cities ADD COLUMN IF NOT EXISTS is_free BOOLEAN DEFAULT false;

ALTER TABLE cities ADD COLUMN IF NOT EXISTS subscription_price NUMERIC DEFAULT 2.99;

-- Create user_cities table for purchased cities
CREATE TABLE IF NOT EXISTS user_cities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  city_name TEXT NOT NULL,
  country TEXT NOT NULL,
  purchased_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, city_name, country)
);

-- Create index for user lookups
CREATE INDEX IF NOT EXISTS idx_user_cities_user_id ON user_cities(user_id);
CREATE INDEX IF NOT EXISTS idx_user_cities_city ON user_cities(city_name, country);

-- Enable Row Level Security
ALTER TABLE user_cities ENABLE ROW LEVEL SECURITY;

-- For development/testing: Allow public access
CREATE POLICY "Allow public read access on user_cities"
ON user_cities FOR SELECT USING (true);

CREATE POLICY "Allow public insert access on user_cities"
ON user_cities FOR INSERT WITH CHECK (true);

-- Verify columns were added
SELECT
    table_name,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_name = 'cities' AND column_name IN ('is_free', 'subscription_price');
