-- Create cities table for manual city management
CREATE TABLE IF NOT EXISTS cities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  country TEXT NOT NULL,
  country_code TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE cities ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access to cities"
ON cities FOR SELECT
USING (is_active = true);

-- Insert popular tourist cities
INSERT INTO cities (name, country, country_code, latitude, longitude, sort_order) VALUES
-- Europe
('Amsterdam', 'Netherlands', 'NL', 52.3676, 4.9041, 1),
('Athens', 'Greece', 'GR', 37.9838, 23.7275, 2),
('Barcelona', 'Spain', 'ES', 41.3851, 2.1734, 3),
('Berlin', 'Germany', 'DE', 52.5200, 13.4050, 4),
('Budapest', 'Hungary', 'HU', 47.4979, 19.0402, 5),
('Copenhagen', 'Denmark', 'DK', 55.6761, 12.5683, 6),
('Dublin', 'Ireland', 'IE', 53.3498, -6.2603, 7),
('Edinburgh', 'UK', 'GB', 55.9533, -3.1883, 8),
('Florence', 'Italy', 'IT', 43.7696, 11.2558, 9),
('Istanbul', 'Turkey', 'TR', 41.0082, 28.9784, 10),
('Lisbon', 'Portugal', 'PT', 38.7223, -9.1393, 11),
('London', 'UK', 'GB', 51.5074, -0.1278, 12),
('Madrid', 'Spain', 'ES', 40.4168, -3.7038, 13),
('Milan', 'Italy', 'IT', 45.4642, 9.1900, 14),
('Oslo', 'Norway', 'NO', 59.9139, 10.7522, 15),
('Paris', 'France', 'FR', 48.8566, 2.3522, 16),
('Prague', 'Czech Republic', 'CZ', 50.0755, 14.4378, 17),
('Reykjavik', 'Iceland', 'IS', 64.1466, -21.9426, 18),
('Rome', 'Italy', 'IT', 41.9028, 12.4964, 19),
('Stockholm', 'Sweden', 'SE', 59.3293, 18.0686, 20),
('Venice', 'Italy', 'IT', 45.4408, 12.3155, 21),
('Vienna', 'Austria', 'AT', 48.2082, 16.3738, 22),
('Zurich', 'Switzerland', 'CH', 47.3769, 8.5417, 23),

-- Asia
('Bangkok', 'Thailand', 'TH', 13.7563, 100.5018, 24),
('Beijing', 'China', 'CN', 39.9042, 116.4074, 25),
('Dubai', 'UAE', 'AE', 25.2048, 55.2708, 26),
('Hong Kong', 'China', 'HK', 22.3193, 114.1694, 27),
('Jakarta', 'Indonesia', 'ID', -6.2088, 106.8456, 28),
('Kyoto', 'Japan', 'JP', 35.0116, 135.7681, 29),
('Mumbai', 'India', 'IN', 19.0760, 72.8777, 30),
('Seoul', 'South Korea', 'KR', 37.5665, 126.9780, 31),
('Shanghai', 'China', 'CN', 31.2304, 121.4737, 32),
('Singapore', 'Singapore', 'SG', 1.3521, 103.8198, 33),
('Taipei', 'Taiwan', 'TW', 25.0330, 121.5654, 34),
('Tokyo', 'Japan', 'JP', 35.6762, 139.6503, 35),

-- Americas
('Buenos Aires', 'Argentina', 'AR', -34.6037, -58.3816, 36),
('Cancun', 'Mexico', 'MX', 21.1619, -86.8515, 37),
('Chicago', 'USA', 'US', 41.8781, -87.6298, 38),
('Cusco', 'Peru', 'PE', -13.5317, -71.9673, 39),
('Havana', 'Cuba', 'CU', 23.1136, -82.3666, 40),
('Las Vegas', 'USA', 'US', 36.1699, -115.1398, 41),
('Los Angeles', 'USA', 'US', 34.0522, -118.2437, 42),
('Miami', 'USA', 'US', 25.7617, -80.1918, 43),
('Mexico City', 'Mexico', 'MX', 19.4326, -99.1332, 44),
('Montreal', 'Canada', 'CA', 45.5017, -73.5673, 45),
('New York', 'USA', 'US', 40.7128, -74.0060, 46),
('Rio de Janeiro', 'Brazil', 'BR', -22.9068, -43.1729, 47),
('San Francisco', 'USA', 'US', 37.7749, -122.4194, 48),
('Seattle', 'USA', 'US', 47.6062, -122.3321, 49),
('Toronto', 'Canada', 'CA', 43.6532, -79.3832, 50),
('Vancouver', 'Canada', 'CA', 49.2827, -123.1207, 51),
('Washington DC', 'USA', 'US', 38.9072, -77.0369, 52),

-- Oceania
('Auckland', 'New Zealand', 'NZ', -36.8485, 174.7633, 53),
('Brisbane', 'Australia', 'AU', -27.4698, 153.0251, 54),
('Melbourne', 'Australia', 'AU', -37.8136, 144.9631, 55),
('Sydney', 'Australia', 'AU', -33.8688, 151.2093, 56),

-- Africa
('Cape Town', 'South Africa', 'ZA', -33.9249, 18.4241, 57),
('Cairo', 'Egypt', 'EG', 30.0444, 31.2357, 58),
('Marrakech', 'Morocco', 'MA', 31.6295, -7.9811, 59)
ON CONFLICT (name, country) DO NOTHING;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_cities_active_sorted ON cities(is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_cities_name ON cities(name);

-- Create a function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at
DROP TRIGGER IF EXISTS update_cities_updated_at ON cities;
CREATE TRIGGER update_cities_updated_at
    BEFORE UPDATE ON cities
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
